baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.6.1"
rd_jar_name: "rundeck-launcher-2.6.1.jar"
rd_jar_sha: "982ca32ffcc8eac4f97ee6b156b46d6c31a52a8e"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.6.1.jar"
rd_jar_size: "85783862"
rd_deb_name: "rundeck-2.6.1-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.6.1-1-GA.deb"
rd_deb_sha: "39ee3b573185b9cedd57f838dd38c96104f8d184"
rd_deb_size: "98812898"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.6.1"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.6.1"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.6.1/RELEASE.md"
markdown: kramdown
