baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.6.8"
rd_jar_name: "rundeck-launcher-2.6.8.jar"
rd_jar_sha: "5a5976ac3b76e64ac5296e1e62576f762869b9be"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.6.8.jar"
rd_jar_size: "88601820"
rd_deb_name: "rundeck-2.6.8-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.6.8-1-GA.deb"
rd_deb_sha: "865c669c8694a9b6fa595363c9906cf771818337"
rd_deb_size: "101245450"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.6.8"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.6.8"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.6.8/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author:
  twitter: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png