baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.10.1"
rd_jar_name: "rundeck-launcher-2.10.1.jar"
rd_jar_sha: "c98b09835be9f5fcb8602e34125e8a3e5aade86a"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.10.1.jar"
rd_jar_size: "100234913"
rd_deb_name: "rundeck-2.10.1-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.10.1-1-GA.deb"
rd_deb_sha: "551ddf2593175bf00a58927beb15302e615bc777"
rd_deb_size: "111300712"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.10.1"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.10.1"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.10.1/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
