baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.9.2"
rd_jar_name: "rundeck-launcher-2.9.2.jar"
rd_jar_sha: "ecb8f75a06b37b2c942840e35534adc0d28ffb6e"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.9.2.jar"
rd_jar_size: "98927957"
rd_deb_name: "rundeck-2.9.2-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.9.2-1-GA.deb"
rd_deb_sha: "d7b59d5b6267da2a7250628e232d7fe9abee99f4"
rd_deb_size: "114036396"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.9.2"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.9.2"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.9.2/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
