rd_version: "1.4.3"
rd_jar_name: "rundeck-launcher-1.4.3.jar"
rd_jar_sha: "a39eec48754ad3be4729e61061ae740e5c128bb2"
rd_jar_url: "https://github.com/downloads/dtolabs/rundeck/rundeck-launcher-1.4.3.jar"
rd_jar_size: "45246085"
rd_deb_name: "rundeck-1.4.3-1.deb"
rd_deb_url: "https://github.com/downloads/dtolabs/rundeck/rundeck-1.4.3-1.deb"
rd_deb_sha: "0cd04c431396cfd097b97ac824aa97c5b49ada3e"
rd_deb_size: "49509812"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v1.4.3"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v1.4.3"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v1.4.3/RELEASE.md"
