rd_version: "1.4.4"
rd_jar_name: "rundeck-launcher-1.4.4.jar"
rd_jar_sha: "fdb2c3af052510363c4354fa85108832f00ddb1f"
rd_jar_url: "https://github.com/downloads/dtolabs/rundeck/rundeck-launcher-1.4.4.jar"
rd_jar_size: "44409697"
rd_deb_name: "rundeck-1.4.4-1.deb"
rd_deb_url: "https://github.com/downloads/dtolabs/rundeck/rundeck-1.4.4-1.deb"
rd_deb_sha: "0fd8656fe70e62001fb253c8ad894715411d6d9c"
rd_deb_size: "47252244"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v1.4.4"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v1.4.4"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v1.4.4/RELEASE.md"
