baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.2.3"
rd_jar_name: "rundeck-launcher-2.2.3.jar"
rd_jar_sha: "44e96e764d079576853230f18c9c7f98c5bf42e8"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.2.3.jar"
rd_jar_size: "57178511"
rd_deb_name: "rundeck-2.2.3-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.2.3-1-GA.deb"
rd_deb_sha: "a11d378abcbbbe88c3c09b94665785893cef3686"
rd_deb_size: "62095204"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v2.2.3"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v2.2.3"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v2.2.3/RELEASE.md"
markdown: kramdown
