baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.6.2"
rd_jar_name: "rundeck-launcher-2.6.2.jar"
rd_jar_sha: "dbe40e429cf6d70e1987959186b032d88b3f9eb7"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.6.2.jar"
rd_jar_size: "86155030"
rd_deb_name: "rundeck-2.6.2-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.6.2-1-GA.deb"
rd_deb_sha: "06530d337b6de3334ee0ff6c6467f1d6323022c3"
rd_deb_size: "99058008"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.6.2"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.6.2"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.6.2/RELEASE.md"
markdown: kramdown
