rd_version: "1.4.5"
rd_jar_name: "rundeck-launcher-1.4.5.jar"
rd_jar_sha: "c635ec4ee695b9169dff42db52a556a17a772e4e"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-1.4.5.jar"
rd_jar_size: "44448979"
rd_deb_name: "rundeck-1.4.5-1.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-1.4.5-1.deb"
rd_deb_sha: "4928d78925312ed4af15a2244b9bf7cc40dd2cd4"
rd_deb_size: "47283742"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v1.4.5"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v1.4.5"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v1.4.5/RELEASE.md"
