baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.2.0"
rd_jar_name: "rundeck-launcher-2.2.0.jar"
rd_jar_sha: "fb9644017fe01a6eac21f6a5bdc5b4455f9d8ab5"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.2.0.jar"
rd_jar_size: "56822589"
rd_deb_name: "rundeck-2.2.0-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.2.0-1-GA.deb"
rd_deb_sha: "3cfabbefbcbc28df05b30af4f54537c740623e44"
rd_deb_size: "62122606"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v2.2.0"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v2.2.0"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v2.2.0/RELEASE.md"
markdown: kramdown
