baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.2.2"
rd_jar_name: "rundeck-launcher-2.2.2.jar"
rd_jar_sha: "50e73a1e360ec0b6dc5a309d3298bda6503b6937"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.2.2.jar"
rd_jar_size: "57183674"
rd_deb_name: "rundeck-2.2.2-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.2.2-1-GA.deb"
rd_deb_sha: "2b757c5e7c78e9e77717d406c7acc5f896fa6d52"
rd_deb_size: "62086200"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v2.2.2"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v2.2.2"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v2.2.2/RELEASE.md"
markdown: kramdown
