baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.5.3"
rd_jar_name: "rundeck-launcher-2.5.3.jar"
rd_jar_sha: "2617113860349b3bbbf953ee96f536a2e8663144"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.5.3.jar"
rd_jar_size: "82135892"
rd_deb_name: "rundeck-2.5.3-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.5.3-1-GA.deb"
rd_deb_sha: "593999dae9e2f600cda9cc17ce575a820f36e0f8"
rd_deb_size: "90791466"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.5.3"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.5.3"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.5.3/RELEASE.md"
markdown: kramdown
