rd_version: "1.5"
rd_jar_name: "rundeck-launcher-1.5.jar"
rd_jar_sha: "9d4b2c51e5d3e67a43ded56ba1a31d781f2432a0"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-1.5.jar"
rd_jar_size: "50849765"
rd_deb_name: "rundeck-1.5-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-1.5-1-GA.deb"
rd_deb_sha: "d1b9ab4479688327fef35f1ae01bf882c2ae5729"
rd_deb_size: "53402222"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v1.5"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v1.5"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v1.5/RELEASE.md"
permalink: /plugins/:title/
