baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.6.3"
rd_jar_name: "rundeck-launcher-2.6.3.jar"
rd_jar_sha: "c131c05de6303fc911140e5fd3c0ce692a7508c1"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.6.3.jar"
rd_jar_size: "86970821"
rd_deb_name: "rundeck-2.6.3-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.6.3-1-GA.deb"
rd_deb_sha: "aa28b2eb1df69e2bfc30aaa4bbd3af01f6dcc58d"
rd_deb_size: "99799690"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.6.3"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.6.3"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.6.3/RELEASE.md"
markdown: kramdown
