baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.10.3"
rd_jar_name: "rundeck-launcher-2.10.3.jar"
rd_jar_sha: "904a8ae4925d46f7743a0cb6e711799c37bf4f79"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.10.3.jar"
rd_jar_size: "100276014"
rd_deb_name: "rundeck_2.10.3-1-GA_all.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck_2.10.3-1-GA_all.deb"
rd_deb_sha: "91ea1194376a1ecafba49e60f5265ea38ab2c4db"
rd_deb_size: "111323426"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.10.3"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.10.3"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.10.3/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
