baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.2.1"
rd_jar_name: "rundeck-launcher-2.2.1.jar"
rd_jar_sha: "80a8bed84557ca647c26c8a81dcdcdae43f34c2e"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.2.1.jar"
rd_jar_size: "56858931"
rd_deb_name: "rundeck-2.2.1-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.2.1-1-GA.deb"
rd_deb_sha: "69ac7f21a64b3f2fef86b4a71a8bf93a02eb7a21"
rd_deb_size: "62167778"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v2.2.1"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v2.2.1"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v2.2.1/RELEASE.md"
markdown: kramdown
