baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.10.0"
rd_jar_name: "rundeck-launcher-2.10.0.jar"
rd_jar_sha: "3ab683a614d22af0338b8b5194a3e07105d3979d"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.10.0.jar"
rd_jar_size: "99529206"
rd_deb_name: "rundeck-2.10.0-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.10.0-1-GA.deb"
rd_deb_sha: "82305bc5c92c4b5300af84613dc82942aff05e7a"
rd_deb_size: "114465386"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.10.0"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.10.0"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.10.0/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
