baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.0.2"
rd_jar_name: "rundeck-launcher-2.0.2.jar"
rd_jar_sha: "89f5788003472fa6add79ca85158e605da01caab"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.0.2.jar"
rd_jar_size: "55966482"
rd_deb_name: "rundeck-2.0.2-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.0.2-1-GA.deb"
rd_deb_sha: "7d9508ea051e056f50c5a9883f3fa6613f5f0062"
rd_deb_size: "62287286"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v2.0.2"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v2.0.2"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v2.0.2/RELEASE.md"
