baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.6.5"
rd_jar_name: "rundeck-launcher-2.6.5.jar"
rd_jar_sha: "e6d24a930d06d80aff62daac404bffaabb9af2f5"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.6.5.jar"
rd_jar_size: "88388401"
rd_deb_name: "rundeck-2.6.5-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.6.5-1-GA.deb"
rd_deb_sha: "0eece7ebb8c90a9d06c32695a6ccbc3c513d8640"
rd_deb_size: "101004532"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.6.5"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.6.5"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.6.5/RELEASE.md"
markdown: kramdown
