rd_version: "1.5"
rd_jar_name: "rundeck-launcher-1.5.jar"
rd_jar_sha: "13b8bb494a5e9d9caf393b060b7397a2887c27b7"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-1.5.jar"
rd_jar_size: "50849539"
rd_deb_name: "rundeck-1.5-0-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-1.5-0-GA.deb"
rd_deb_sha: "9390bfcc0cfaf029ee1eef7afa63a9d412f02b70"
rd_deb_size: "53402072"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v1.5"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v1.5"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v1.5/RELEASE.md"
