rd_version: "1.4.0.2"
rd_jar_name: "rundeck-launcher-1.4.0.2.jar"
rd_jar_sha: "40c8293b10ae1e7bf5f6beca5b9b7a73a836da22"
rd_jar_url: "https://github.com/downloads/dtolabs/rundeck/rundeck-launcher-1.4.0.2.jar"
rd_jar_size: "46152971"
rd_deb_name: "rundeck-1.4.0.2-1.deb"
rd_deb_url: "https://github.com/downloads/dtolabs/rundeck/rundeck-1.4.0.2-1.deb"
rd_deb_sha: "dc9aa08dcb3c883cf97309966e94ea5bdee295b4"
rd_deb_size: "48246164"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v1.4.0.2"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v1.4.0.2"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v1.4.0.2/RELEASE.md"
