baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.4.1"
rd_jar_name: "rundeck-launcher-2.4.1.jar"
rd_jar_sha: "ea3f85974787825d9fdb0b381ad6132e7b5d77a7"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.4.1.jar"
rd_jar_size: "60634246"
rd_deb_name: "rundeck-2.4.1-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.4.1-1-GA.deb"
rd_deb_sha: "5ce117bc994c6911bfbd46cc6a7f58b76e2e228f"
rd_deb_size: "60567884"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.4.1"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.4.1"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.4.1/RELEASE.md"
markdown: kramdown
