baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.6.0"
rd_jar_name: "rundeck-launcher-2.6.0.jar"
rd_jar_sha: "de93668360a9e9b1e28693c11fe564b5b973a06b"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.6.0.jar"
rd_jar_size: "85762635"
rd_deb_name: "rundeck-2.6.0-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.6.0-1-GA.deb"
rd_deb_sha: "dbaa99a0deff78f470b7d674a681e6175596b04a"
rd_deb_size: "98820440"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.6.0"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.6.0"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.6.0/RELEASE.md"
markdown: kramdown
