baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.6.11"
rd_jar_name: "rundeck-launcher-2.6.11.jar"
rd_jar_sha: "3af60488a29e2fdd56b1139c8cf0d65c6bde34db"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.6.11.jar"
rd_jar_size: "88241586"
rd_deb_name: "rundeck-2.6.11-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.6.11-1-GA.deb"
rd_deb_sha: "a14d864a5f24ba756097e485a54ea71fc6d0253a"
rd_deb_size: "100576714"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.6.11"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.6.11"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.6.11/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author:
  twitter: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png