rd_version: "1.4.2.1"
rd_jar_name: "rundeck-launcher-1.4.2.1.jar"
rd_jar_sha: "4f05f020546eed9a342ce85a5c213d53c57fa594"
rd_jar_url: "https://github.com/downloads/dtolabs/rundeck/rundeck-launcher-1.4.2.1.jar"
rd_jar_size: "46521667"
rd_deb_name: "rundeck-1.4.2.1-1.deb"
rd_deb_url: "https://github.com/downloads/dtolabs/rundeck/rundeck-1.4.2.1-1.deb"
rd_deb_sha: "d9af5f4536bfd26243e21fc42317d02126a4f688"
rd_deb_size: "48252998"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v1.4.2.1"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v1.4.2.1"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v1.4.2.1/RELEASE.md"
