baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.9.0"
rd_jar_name: "rundeck-launcher-2.9.0.jar"
rd_jar_sha: "26563247248f521734f13237638cb3f373d33620"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.9.0.jar"
rd_jar_size: "98924577"
rd_deb_name: "rundeck-2.9.0-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.9.0-1-GA.deb"
rd_deb_sha: "d16c22beb654449d9022c8e8e915ecb5c145ff68"
rd_deb_size: "114032312"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.9.0"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.9.0"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.9.0/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
