baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.1.2"
rd_jar_name: "rundeck-launcher-2.1.2.jar"
rd_jar_sha: "91545f370776297e4e65df39cc231854faef042d"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.1.2.jar"
rd_jar_size: "56723584"
rd_deb_name: "rundeck-2.1.2-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.1.2-1-GA.deb"
rd_deb_sha: "1d3edf0d329b7b41853d802be50f0facc74dfc94"
rd_deb_size: "62035310"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v2.1.2"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v2.1.2"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v2.1.2/RELEASE.md"
markdown: kramdown
