baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.6.4"
rd_jar_name: "rundeck-launcher-2.6.4.jar"
rd_jar_sha: "985c4e9c75ee42ea7314a255599b3420022502c7"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.6.4.jar"
rd_jar_size: "86986469"
rd_deb_name: "rundeck-2.6.4-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.6.4-1-GA.deb"
rd_deb_sha: "9ff030fc8ec285253026333c1588439c2aaa1e61"
rd_deb_size: "99813060"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.6.4"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.6.4"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.6.4/RELEASE.md"
markdown: kramdown
