baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.7.3"
rd_jar_name: "rundeck-launcher-2.7.3.jar"
rd_jar_sha: "daf9485f3dca4413cec9f0dadd21e375da7fbedf"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.7.3.jar"
rd_jar_size: "91728838"
rd_deb_name: "rundeck-2.7.3-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.7.3-1-GA.deb"
rd_deb_sha: "a75bec02ced46b14025f0e0c8d70282d98e7bc69"
rd_deb_size: "105846222"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.7.3"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.7.3"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.7.3/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author:
  twitter: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png