rd_version: "1.4.1"
rd_jar_name: "rundeck-launcher-1.4.1.jar"
rd_jar_sha: "f1b147f647113b3fc7993c4b39b28aaf0e423f8f"
rd_jar_url: "https://github.com/downloads/dtolabs/rundeck/rundeck-launcher-1.4.1.jar"
rd_jar_size: "46032098"
rd_deb_name: "rundeck-1.4.1-1.deb"
rd_deb_url: "https://github.com/downloads/dtolabs/rundeck/rundeck-1.4.1-1.deb"
rd_deb_sha: "ed61a01edcc940a389e3e259cf9851859867c4ce"
rd_deb_size: "47984332"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v1.4.1"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v1.4.1"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v1.4.1/RELEASE.md"
