baseurl: ""
url: ""
rd_version: "1.6.2"
rd_jar_name: "rundeck-launcher-1.6.2.jar"
rd_jar_sha: "ef4ef48a023b238a5a381941bd9cab0f93e74634"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-1.6.2.jar"
rd_jar_size: "50259382"
rd_deb_name: "rundeck-1.6.2-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-1.6.2-1-GA.deb"
rd_deb_sha: "31c2f6091fdc22f10080ba2ef6ffdc51536af7cc"
rd_deb_size: "55890708"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v1.6.2"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v1.6.2"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v1.6.2/RELEASE.md"
