baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.10.7"
rd_jar_name: "rundeck-launcher-2.10.7.jar"
rd_jar_sha: "5bc0ab83929df79e2a2e9983b1bf5545d133d6cf"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.10.7.jar"
rd_jar_size: "100282142"
rd_deb_name: "rundeck_2.10.7-1-GA_all.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck_2.10.7-1-GA_all.deb"
rd_deb_sha: "baf0d7c1f72bdb0533b2b3fb2e7349e8949b5892"
rd_deb_size: "111323546"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.10.7"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.10.7"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.10.7/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
