baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.9.1"
rd_jar_name: "rundeck-launcher-2.9.1.jar"
rd_jar_sha: "b19f4ffb5f8532695b5732d63d742cb5c86affda"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.9.1.jar"
rd_jar_size: "98927785"
rd_deb_name: "rundeck-2.9.1-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.9.1-1-GA.deb"
rd_deb_sha: "514930d72da63b4c297a5a8704c4f94015ba5575"
rd_deb_size: "114036868"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.9.1"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.9.1"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.9.1/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
