baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.6.9"
rd_jar_name: "rundeck-launcher-2.6.9.jar"
rd_jar_sha: "8879caf623465902cb039921ce157d77e8e0592f"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.6.9.jar"
rd_jar_size: "89411126"
rd_deb_name: "rundeck-2.6.9-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.6.9-1-GA.deb"
rd_deb_sha: "47084f2367e6a1d3b873fc883b65d9dd2ece32b8"
rd_deb_size: "102011522"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.6.9"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.6.9"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.6.9/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author:
  twitter: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png