rd_version: "1.5.2"
rd_jar_name: "rundeck-launcher-1.5.2.jar"
rd_jar_sha: "1bb74602ed13db7121969a8832e3278fe3297d65"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-1.5.2.jar"
rd_jar_size: "  File: "../tmp/rundeck-launcher-1.5.2.jar"
    ID: 1973e42d2bcf3791 Namelen: 255     Type: ext2/ext3
Block size: 4096       Fundamental block size: 4096
Blocks: Total: 24512935   Free: 17943715   Available: 16698531
Inodes: Total: 12451840   Free: 11927256"
rd_deb_name: "rundeck-1.5.2-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-1.5.2-1-GA.deb"
rd_deb_sha: "987f662b0b91b882865cb719e6b1bb603314c52d"
rd_deb_size: "  File: "../tmp/rundeck-1.5.2-1-GA.deb"
    ID: 1973e42d2bcf3791 Namelen: 255     Type: ext2/ext3
Block size: 4096       Fundamental block size: 4096
Blocks: Total: 24512935   Free: 17930623   Available: 16685439
Inodes: Total: 12451840   Free: 11927255"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v1.5.2"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v1.5.2"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v1.5.2/RELEASE.md"
