rd_version: "1.4.2"
rd_jar_name: "rundeck-launcher-1.4.2.jar"
rd_jar_sha: "5216d7556739181edbf870b80610074e90839051"
rd_jar_url: "https://github.com/downloads/dtolabs/rundeck/rundeck-launcher-1.4.2.jar"
rd_jar_size: "46521327"
rd_deb_name: "rundeck-1.4.2-1.deb"
rd_deb_url: "https://github.com/downloads/dtolabs/rundeck/rundeck-1.4.2-1.deb"
rd_deb_sha: "d0b0234128d7c6c3e1b330da7a94ba001a3678e0"
rd_deb_size: "48265700"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v1.4.2"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v1.4.2"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v1.4.2/RELEASE.md"
