baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.0.3"
rd_jar_name: "rundeck-launcher-2.0.3.jar"
rd_jar_sha: "641bfb1b2f0ebf5e039d8d667102f0afbe9259ad"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.0.3.jar"
rd_jar_size: "55966223"
rd_deb_name: "rundeck-2.0.3-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.0.3-1-GA.deb"
rd_deb_sha: "1a0ce703e49ba757d39c160580136f7718ec57ff"
rd_deb_size: "62287480"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v2.0.3"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v2.0.3"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v2.0.3/RELEASE.md"
