baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.1.0"
rd_jar_name: "rundeck-launcher-2.1.0.jar"
rd_jar_sha: "adc9fe05e685c8cb1986a40625e6e1563bfbe751"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.1.0.jar"
rd_jar_size: "56555712"
rd_deb_name: "rundeck-2.1.0-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.1.0-1-GA.deb"
rd_deb_sha: "c6097cd7ec883675bc94081b5ccf65da288ee544"
rd_deb_size: "61892920"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v2.1.0"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v2.1.0"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v2.1.0/RELEASE.md"
