baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.10.2"
rd_jar_name: "rundeck-launcher-2.10.2.jar"
rd_jar_sha: "cc1eba8868c6a9304b04c34a8ca2c7e572111929"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.10.2.jar"
rd_jar_size: "100257331"
rd_deb_name: "rundeck-2.10.2-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.10.2-1-GA.deb"
rd_deb_sha: "b72710dd88081995ba8c22b147922653108198a9"
rd_deb_size: "111305590"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.10.2"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.10.2"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.10.2/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
