baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.9.4"
rd_jar_name: "rundeck-launcher-2.9.4.jar"
rd_jar_sha: "9e0b3878660f6898cfd2e154d77a3947148a7b8d"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.9.4.jar"
rd_jar_size: "99092057"
rd_deb_name: "rundeck-2.9.4-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.9.4-1-GA.deb"
rd_deb_sha: "e1b68ea80f95dfe8fdc8f2d61fa2b9f764f23fe6"
rd_deb_size: "114193828"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.9.4"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.9.4"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.9.4/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
