rd_version: "1.5.3"
rd_jar_name: "rundeck-launcher-1.5.3.jar"
rd_jar_sha: "59457766de3cdb3fcb45fa7b4e8adf73fddfae9d"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-1.5.3.jar"
rd_jar_size: "48347361"
rd_deb_name: "rundeck-1.5.3-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-1.5.3-1-GA.deb"
rd_deb_sha: "f01b9c8b5c0b51684e0ce714b026bceba308b55c"
rd_deb_size: "53656544"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v1.5.3"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v1.5.3"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v1.5.3/RELEASE.md"
