baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.6.10"
rd_jar_name: "rundeck-launcher-2.6.10.jar"
rd_jar_sha: "aada7608c743a162314487b9d7f7abe006296347"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.6.10.jar"
rd_jar_size: "88241347"
rd_deb_name: "rundeck-2.6.10-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.6.10-1-GA.deb"
rd_deb_sha: "7c6920591457a7cbed8087ced882285e63ebf6dd"
rd_deb_size: "100573424"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.6.10"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.6.10"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.6.10/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author:
  twitter: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png