baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.0.4"
rd_jar_name: "rundeck-launcher-2.0.4.jar"
rd_jar_sha: "2f45cedb28c0e132f327ed3eb16972fcedd6733a"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.0.4.jar"
rd_jar_size: "55983594"
rd_deb_name: "rundeck-2.0.4-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.0.4-1-GA.deb"
rd_deb_sha: "1884a8be62c650b3ee5d89ca49f53da0cc291e4d"
rd_deb_size: "61428996"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v2.0.4"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v2.0.4"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v2.0.4/RELEASE.md"
