rd_version: "1.4.0"
rd_jar_name: "rundeck-launcher-1.4.0.jar"
rd_jar_sha: "42b37fc50f0d7a576a276841e9ed335b9d3aa043"

rd_jar_url: "https://github.com/downloads/dtolabs/rundeck/rundeck-launcher-1.4.0.jar"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v1.4.0"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v1.4.0"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v1.4.0/RELEASE.md"
