baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.3.1"
rd_jar_name: "rundeck-launcher-2.3.1.jar"
rd_jar_sha: "d31f7263141264038407fee7f9852c8f484e3556"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.3.1.jar"
rd_jar_size: "57304127"
rd_deb_name: "rundeck-2.3.1-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.3.1-1-GA.deb"
rd_deb_sha: "0a415c5cd3bb1d27be3aab5c8074fabb407e1beb"
rd_deb_size: "62209922"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v2.3.1"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v2.3.1"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v2.3.1/RELEASE.md"
markdown: kramdown
