baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.6.6"
rd_jar_name: "rundeck-launcher-2.6.6.jar"
rd_jar_sha: "4327248666a0cab2afb8f00555e442fac26c8070"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.6.6.jar"
rd_jar_size: "88395280"
rd_deb_name: "rundeck-2.6.6-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.6.6-1-GA.deb"
rd_deb_sha: "80c34da2897dfd339758d62e3dbfd35ad116d41d"
rd_deb_size: "101012718"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.6.6"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.6.6"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.6.6/RELEASE.md"
markdown: kramdown
