baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.3.2"
rd_jar_name: "rundeck-launcher-2.3.2.jar"
rd_jar_sha: "ccbad3d63074694583772e135ecc5b2920936a6d"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.3.2.jar"
rd_jar_size: "57303309"
rd_deb_name: "rundeck-2.3.2-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.3.2-1-GA.deb"
rd_deb_sha: "812ee51372659659715767ac923bd2a664d84fc2"
rd_deb_size: "62204998"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v2.3.2"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v2.3.2"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v2.3.2/RELEASE.md"
markdown: kramdown
