rd_version: "1.5.2"
rd_jar_name: "rundeck-launcher-1.5.2.jar"
rd_jar_sha: "1bb74602ed13db7121969a8832e3278fe3297d65"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-1.5.2.jar"
rd_jar_size: "48266781"
rd_deb_name: "rundeck-1.5.2-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-1.5.2-1-GA.deb"
rd_deb_sha: "987f662b0b91b882865cb719e6b1bb603314c52d"
rd_deb_size: "53564716"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v1.5.2"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v1.5.2"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v1.5.2/RELEASE.md"
