baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.5.2"
rd_jar_name: "rundeck-launcher-2.5.2.jar"
rd_jar_sha: "51672c37ee5f9631f5865842e8cd0ed948519790"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.5.2.jar"
rd_jar_size: "80271639"
rd_deb_name: "rundeck-2.5.2-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.5.2-1-GA.deb"
rd_deb_sha: "4f801d8ffed357c9d592dd082a431f32637cbdbc"
rd_deb_size: "89961578"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.5.2"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.5.2"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.5.2/RELEASE.md"
markdown: kramdown
