baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.4.2"
rd_jar_name: "rundeck-launcher-2.4.2.jar"
rd_jar_sha: "fdbfe51a769c11e71fe09791605e8e3e11aa41eb"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.4.2.jar"
rd_jar_size: "60634708"
rd_deb_name: "rundeck-2.4.2-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.4.2-1-GA.deb"
rd_deb_sha: "0452d67ec0e9da27be21b3fc73b54fbd7769330b"
rd_deb_size: "60565184"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.4.2"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.4.2"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.4.2/RELEASE.md"
markdown: kramdown
