baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.4.0"
rd_jar_name: "rundeck-launcher-2.4.0.jar"
rd_jar_sha: "dd16219d8ca1f4e320fd4d6b214aae388f9d5819"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.4.0.jar"
rd_jar_size: "60623909"
rd_deb_name: "rundeck-2.4.0-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.4.0-1-GA.deb"
rd_deb_sha: "4f3d669e168e0a68d1ea00a524c8308f6dfa7ae8"
rd_deb_size: "60558048"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v2.4.0"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v2.4.0"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v2.4.0/RELEASE.md"
markdown: kramdown
