baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.10.6"
rd_jar_name: "rundeck-launcher-2.10.6.jar"
rd_jar_sha: "73d2fb95248385c13ed193fd12a0bd55e82dfd06"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.10.6.jar"
rd_jar_size: "100276613"
rd_deb_name: "rundeck_2.10.6-1-GA_all.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck_2.10.6-1-GA_all.deb"
rd_deb_sha: "e2a0fec71a74f98d7f6b82ffa36234a24cc7fce7"
rd_deb_size: "111326410"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.10.6"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.10.6"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.10.6/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
