baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.7.2"
rd_jar_name: "rundeck-launcher-2.7.2.jar"
rd_jar_sha: "409209fc0faf213cb6caaa9cb3d95ff5996efc92"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.7.2.jar"
rd_jar_size: "91663355"
rd_deb_name: "rundeck-2.7.2-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.7.2-1-GA.deb"
rd_deb_sha: "b21b60fd798b044c4b8642d3f568dd882f4e2629"
rd_deb_size: "105782718"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.7.2"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.7.2"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.7.2/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author:
  twitter: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png