rd_version: "1.3.2"
rd_jar_name: "rundeck-launcher-1.3.2.jar"
rd_jar_sha: "7c0535c40b1a4274ca8e5a247980a27e07aa452c"

rd_jar_url: "https://github.com/downloads/dtolabs/rundeck/rundeck-launcher-1.3.2.jar"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v1.3.2"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v1.3.2"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v1.3.2/RELEASE.md"
