baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.0.0"
rd_jar_name: "rundeck-launcher-2.0.0.jar"
rd_jar_sha: "b7f980625770a48c128ed35e86e7958769386a95"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.0.0.jar"
rd_jar_size: "55948219"
rd_deb_name: "rundeck-2.0.0-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.0.0-1-GA.deb"
rd_deb_sha: "2192c64c257e43472ebaa8285151d7a9e1eb22e8"
rd_deb_size: "62312252"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v2.0.0"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v2.0.0"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v2.0.0/RELEASE.md"
