rd_version: "1.5.1"
rd_jar_name: "rundeck-launcher-1.5.1.jar"
rd_jar_sha: "2f86196d7182a8c9b1e508f8cca225fc4bd65296"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-1.5.1.jar"
rd_jar_size: "48266101"
rd_deb_name: "rundeck-1.5.1-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-1.5.1-1-GA.deb"
rd_deb_sha: "269feab4676831dd2a46453f52a9a67b9a6148bb"
rd_deb_size: "53563666"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v1.5.1"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v1.5.1"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v1.5.1/RELEASE.md"
