baseurl: "http://damonedwards.github.io/rundeck-ghpages-damon"
url: "http://damonedwards.github.io/rundeck-ghpages-damon"
rd_version: "1.6.0"
rd_jar_name: "rundeck-launcher-1.6.0.jar"
rd_jar_sha: "b3b6466b52ce3d9bcecbc2649ccd7fedef5b32f0"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-1.6.0.jar"
rd_jar_size: "47929182"
rd_deb_name: "rundeck-1.6.0-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-1.6.0-1-GA.deb"
rd_deb_sha: "e2b79d27bb9859953f7b17a4d2cc9dc9f2489a6c"
rd_deb_size: "53156660"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v1.6.0"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v1.6.0"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v1.6.0/RELEASE.md"
