rd_version: "1.6.1"
rd_jar_name: "rundeck-launcher-1.6.1.jar"
rd_jar_sha: "eddb98e9aa88ddf2ca9fde2e8ef47a495f263c98"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-1.6.1.jar"
rd_jar_size: "49736632"
rd_deb_name: "rundeck-1.6.1-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-1.6.1-1-GA.deb"
rd_deb_sha: "6552e9d2255728c65e6ca5394ff20b92e08c68bc"
rd_deb_size: "55373768"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v1.6.1"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v1.6.1"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v1.6.1/RELEASE.md"
