rd_version: "1.4.0.1"
rd_jar_name: "rundeck-launcher-1.4.0.1.jar"
rd_jar_sha: "3561abd052ade180e2fd96930ae777f99226b23c"

rd_jar_url: "https://github.com/downloads/dtolabs/rundeck/rundeck-launcher-1.4.0.1.jar"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v1.4.0.1"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v1.4.0.1"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v1.4.0.1/RELEASE.md"
