baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.1.1"
rd_jar_name: "rundeck-launcher-2.1.1.jar"
rd_jar_sha: "61eed14d901a65fb0a12f7ab7bb7c266571c8960"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.1.1.jar"
rd_jar_size: "56571392"
rd_deb_name: "rundeck-2.1.1-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.1.1-1-GA.deb"
rd_deb_sha: "5b04ec8212a9590e259c02a4279be541150b89f2"
rd_deb_size: "61913726"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v2.1.1"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v2.1.1"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v2.1.1/RELEASE.md"
markdown: kramdown
