baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.8.2"
rd_jar_name: "rundeck-launcher-2.8.2.jar"
rd_jar_sha: "ec8f99fcb1724dc9fefa13b9ebffd9f34a140218"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.8.2.jar"
rd_jar_size: "92227560"
rd_deb_name: "rundeck-2.8.2-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.8.2-1-GA.deb"
rd_deb_sha: "9d73a71a82181d61ad361ec8852413afe1a37b58"
rd_deb_size: "106270032"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.8.2"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.8.2"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.8.2/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
