baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.5.0"
rd_jar_name: "rundeck-launcher-2.5.0.jar"
rd_jar_sha: "b2f928af35aa016e573196a16d71beb2cc965f0c"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.5.0.jar"
rd_jar_size: "80038763"
rd_deb_name: "rundeck-2.5.0-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.5.0-1-GA.deb"
rd_deb_sha: "92e4ee580c8fdfd360297c07208e6a70ce3cc1b8"
rd_deb_size: "82403936"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.5.0"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.5.0"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.5.0/RELEASE.md"
markdown: kramdown
