baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.5.1"
rd_jar_name: "rundeck-launcher-2.5.1.jar"
rd_jar_sha: "13e559206caa0293aa790cfeb7b7ae4e0e75e8e9"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.5.1.jar"
rd_jar_size: "80073830"
rd_deb_name: "rundeck-2.5.1-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.5.1-1-GA.deb"
rd_deb_sha: "ff27d7a274f484b0b730beaed0b3df2767d0e7b8"
rd_deb_size: "82418928"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.5.1"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.5.1"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.5.1/RELEASE.md"
markdown: kramdown
