baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.3.0"
rd_jar_name: "rundeck-launcher-2.3.0.jar"
rd_jar_sha: "a20bca7b3921cefff38f29b4daa1c54d31366338"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.3.0.jar"
rd_jar_size: "57300850"
rd_deb_name: "rundeck-2.3.0-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.3.0-1-GA.deb"
rd_deb_sha: "d2b33e7b4f738ddbd46ef6b5c799008d08c7f52e"
rd_deb_size: "62197498"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v2.3.0"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v2.3.0"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v2.3.0/RELEASE.md"
markdown: kramdown
