baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.7.0"
rd_jar_name: "rundeck-launcher-2.7.0.jar"
rd_jar_sha: "6ae22770246ba74130081f1c8ff86dc8d5ef13f5"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.7.0.jar"
rd_jar_size: "91662236"
rd_deb_name: "rundeck-2.7.0-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.7.0-1-GA.deb"
rd_deb_sha: "c17cc896aac6c3cefd66faac957ccfd1a086bb1e"
rd_deb_size: "105785444"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.7.0"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.7.0"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.7.0/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author:
  twitter: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png