baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.1.3"
rd_jar_name: "rundeck-launcher-2.1.3.jar"
rd_jar_sha: "ac19abecb38f02073dd92f1da44289b07b26626e"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.1.3.jar"
rd_jar_size: "56731833"
rd_deb_name: "rundeck-2.1.3-1-GA.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck-2.1.3-1-GA.deb"
rd_deb_sha: "71266eb972ba553a3541e92593241bfd188a7cf1"
rd_deb_size: "62037660"
rd_zipball: "https://github.com/dtolabs/rundeck/zipball/v2.1.3"
rd_tarball: "https://github.com/dtolabs/rundeck/tarball/v2.1.3"
rd_releasenotes: "https://github.com/dtolabs/rundeck/blob/v2.1.3/RELEASE.md"
markdown: kramdown
